### PR TITLE
Add ThemeChooser!! :D WIth IntegrateD App Themer!!

### PR DESCRIPTION
**Pull request by pranav01**

### CODE REVIEW

**Comment by pranav01** [comment]
Root is My self! Didnt add ssh key :3

**Comment by pranav01** [comment]
@akhilnarang @W4TCH0UT verify and merge! :3

**Comment by Anik1199** [comment]
@pranav01 it works perfectly?

**Comment by akhilnarang** [comment]
Will test, and Pick

**Comment by pranav01** [comment]
@Anik1199 It does!! WOrks Perfect!!Damn Sure

**Comment by akhilnarang** [comment]
lululululululul

**Pull request closed without merging**
